export default {
    immediate: 1,
    accumulator: 2,
    relative: 3,
    zeroPage: 4,
    zeroPageX: 5,
    zeroPageY: 6,
    absolute: 7,
    absoluteX: 8,
    absoluteY: 9,
    indirect: 10,
    indirectX: 11,
    indirectY: 12,
    none: 13,
};
